FROM python:3.14-slim

COPY ./requirements.txt /app/requirements.txt

RUN cd /app && pip install --no-cache-dir -r requirements.txt

COPY . /app

WORKDIR /app/fishing_store

RUN chmod +x /app/entrypoint.sh