FROM python:3.14-slim

WORKDIR /app/fishing_store

COPY ./requirements.txt /app/requirements.txt

RUN cd /app && pip install --no-cache-dir -r requirements.txt

COPY . /app

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]