# Generated by Django 6.0.3 on 2026-05-07 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FishingRod',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('length', models.FloatField(help_text='Length in meters')),
                ('test_min', models.FloatField(help_text='Minimum test in grams')),
                ('test_max', models.FloatField(help_text='Maximum test in grams')),
                ('material', models.CharField(blank=True, max_length=100)),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('spool_size', models.IntegerField(help_text='Size of the spool (e.g., 2000, 3000)')),
                ('gear_ratio', models.CharField(help_text='e.g., 5.2:1', max_length=20)),
                ('bearings_count', models.PositiveIntegerField(default=1)),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
