# Generated by Django 6.0.3 on 2026-05-08 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fishingrod",
            options={
                "verbose_name": "Рибацька вудка",
                "verbose_name_plural": "Рибацькі вудки",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Рибацький товар",
                "verbose_name_plural": "Рибацькі товари",
            },
        ),
        migrations.AlterModelOptions(
            name="reel",
            options={
                "verbose_name": "Рибацька котушка",
                "verbose_name_plural": "Рибацькі котушки",
            },
        ),
        migrations.AlterModelOptions(
            name="stockalert",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Сповіщення про запас",
                "verbose_name_plural": "Сповіщення про запаси",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата видалення"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Продавець",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fishingrod",
            name="length",
            field=models.FloatField(
                help_text="Довжина в метрах", verbose_name="Довжина"
            ),
        ),
        migrations.AlterField(
            model_name="fishingrod",
            name="material",
            field=models.CharField(blank=True, max_length=100, verbose_name="Матеріал"),
        ),
        migrations.AlterField(
            model_name="fishingrod",
            name="test_max",
            field=models.FloatField(
                help_text="Максимальний тест у грамах", verbose_name="Тест (макс)"
            ),
        ),
        migrations.AlterField(
            model_name="fishingrod",
            name="test_min",
            field=models.FloatField(
                help_text="Мінімальний тест у грамах", verbose_name="Тест (мін)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="Зображення"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Поріг низького запасу"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Ціна"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Кількість на складі"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
        ),
        migrations.AlterField(
            model_name="reel",
            name="bearings_count",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Кількість підшипників"
            ),
        ),
        migrations.AlterField(
            model_name="reel",
            name="gear_ratio",
            field=models.CharField(
                help_text="Наприклад, 5.2:1",
                max_length=20,
                verbose_name="Передавальне число",
            ),
        ),
        migrations.AlterField(
            model_name="reel",
            name="spool_size",
            field=models.IntegerField(
                help_text="Розмір шпулі (наприклад, 2000, 3000)",
                verbose_name="Розмір шпулі",
            ),
        ),
        migrations.AlterField(
            model_name="stockalert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата виникнення"
            ),
        ),
        migrations.AlterField(
            model_name="stockalert",
            name="current_stock",
            field=models.PositiveIntegerField(verbose_name="Поточний запас"),
        ),
        migrations.AlterField(
            model_name="stockalert",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_alerts",
                to="store.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="stockalert",
            name="status",
            field=models.CharField(
                choices=[("NEW", "Нове"), ("RESOLVED", "Вирішено")],
                default="NEW",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="stockalert",
            name="threshold",
            field=models.PositiveIntegerField(verbose_name="Поріг"),
        ),
    ]
