# Generated by Django 6.0.3 on 2026-05-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_suborder_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='is_active',
        ),
    ]
