# Generated by Django 6.0.3 on 2026-05-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_order_deleted_at_remove_order_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=50, verbose_name="Місто"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="flat_num",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Номер квартири"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="house_num",
            field=models.CharField(max_length=10, verbose_name="Номер будинку"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Номер телефону"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(max_length=25, verbose_name="Поштовий індекс"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(max_length=50, verbose_name="Область"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="street",
            field=models.CharField(max_length=100, verbose_name="Вулиця"),
            preserve_default=False,
        ),
    ]
