# Generated by Django 6.0.3 on 2026-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_order_city_order_flat_num_order_house_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Ім'я користувача"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Прізвище користувача"),
            preserve_default=False,
        ),
    ]
