# Generated by Django 6.0.3 on 2026-04-25 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Область')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Місто')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Назва вулиці')),
                ('house_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер будинку')),
                ('flat_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер квартири')),
                ('postal_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Поштовий індекс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Область')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Місто')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Назва вулиці')),
                ('house_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер будинку')),
                ('flat_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер квартири')),
                ('postal_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Поштовий індекс')),
                ('store_name', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
