# Generated by Django 6.0.3 on 2026-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_customuser_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я користувача"),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Прізвище користувача'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я користувача"),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Прізвище користувача'),
        ),
    ]
