# Generated by Django 6.0.3 on 2026-05-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customerprofile_first_name_customerprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='flat_num',
            field=models.CharField(blank=True, null=True, verbose_name='Номер квартири'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='house_num',
            field=models.CharField(blank=True, null=True, verbose_name='Номер будинку'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='flat_num',
            field=models.CharField(blank=True, null=True, verbose_name='Номер квартири'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='house_num',
            field=models.CharField(blank=True, null=True, verbose_name='Номер будинку'),
        ),
    ]
